spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OnlineSchool 
    username: postgres # пользователь
    password: passkey # пароль
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  thymeleaf:
    cache: false

server:
  port: 8081
